# Generated by Django 4.2.28 on 2026-02-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_task_assigned_to_task_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudokugame',
            name='mistakes',
            field=models.IntegerField(default=0),
        ),
    ]
