# Generated by Django 4.2.28 on 2026-02-08 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_sudokugame_mistakes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicTacToeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.JSONField(default=list)),
                ('current_turn', models.CharField(default='X', max_length=1)),
                ('winner', models.CharField(blank=True, max_length=1, null=True)),
                ('is_draw', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tictactoe_game', to='core.circle')),
                ('player_o', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tictactoe_o', to=settings.AUTH_USER_MODEL)),
                ('player_x', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tictactoe_x', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
